FROM mengdemao/docker-base:latest

VOLUME /bin

USER root
COPY ./compiler_entry.sh /bin/compiler_entry.sh
RUN ["chmod", "+x", "/bin/compiler_entry.sh"]
USER mengdemao

ENTRYPOINT ["/bin/compiler_entry.sh"]
