FROM mengdemao/docker-base:latest

VOLUME /bin

USER root
COPY ./crosstool_entry.sh /bin/crosstool_entry.sh
RUN ["chmod", "+x", "/bin/crosstool_entry.sh"]
USER mengdemao

ENTRYPOINT ["/bin/crosstool_entry.sh"]
